FROM python:3.10-slim-bookworm

# install SUNDIALS
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        libsundials-dev \
    \
    && rm -rf /var/lib/apt/lists

# install Python requirements for assimulo
RUN pip install "cython<1.0" numpy scipy matplotlib

ARG ASSIMULO_VERSION=3.4.3
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        g++ \
        libblas-dev \
        liblapack-dev \
        git \
    \
    && pip install --install-option="--optimize=1" \
            --install-option="--extra-fortran-link-flags=-shared" \
            --install-option="--sundials-home=/usr" \
            --install-option="--blas-home=/usr/lib/x86_64-linux-gnu" \
            --install-option="--lapack-home=/usr" \
            --install-option="--extra-fortran-compile-flags=-fallow-argument-mismatch"  \
            --install-option="--extra-c-flags=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION" \
            git+https://github.com/modelon-community/Assimulo.git@Assimulo-${ASSIMULO_VERSION}  \
    \
    && apt-get remove -y \
        g++ \
        liblas-dev \
        liblapack-dev \
        git \
    \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists

# fonts for matplotlib
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends libfreetype6 \
    && rm -rf /var/lib/apt/lists/*
