name: pysces
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - assimulo
  - pip:
    - python-libsbml
    - matplotlib
    - "git+https://github.com/PySCeS/pysces.git@assimulo#egg=pysces"
